# step 1: create a cloudsql postgres db with database name as "keycloak"
# step 2: create a db user with username as "keycloakuser" and password as "b*********0Bcn"
# step 3: kubectl create secret generic cloudsqlsecret --from-literal=db_host=<YOUR-PRIVATE-IP-ADDRESS> -n kc-azure-prod
# step 4: kubectl apply -f keycloak-secrets.yml -n kc-azure-prod

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: kc-azure-prod
type: Opaque
stringData:
  KC_DB_USERNAME: "keycloakuser"
  KC_DB_PASSWORD: "b*********0Bcn"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://<YOUR-PRIVATE-IP-ADDRESS>:<DB-PORT>/keycloak"

  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: "keycloak"
  
  KEYCLOAK_ADMIN: <KEYCLOAK-ADMIN-USERNAME>
  KEYCLOAK_ADMIN_PASSWORD: <KEYCLOAK-ADMIN-PASSWORD>
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED : "true"
  KC_LOG_LEVEL: INFO
  KC_HOSTNAME_DEBUG: "true"
  KC_HOSTNAME_STRICT_HTTPS: "true"
  KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
  KC_HOSTNAME: <DOMAIN-NAME>
  KC_HOSTNAME_ADMIN: <DOMAIN-NAME>  # e.g login.mywebsite.com
  KC_HTTP_ENABLED: "false"
  PROXY_ADDRESS_FORWARDING: "true"
  KC_PROXY: edge
