# kubectl apply -f tls-secrets-cert-mngr.yml -n kc-azure-prod

apiVersion: v1
kind: Secret
metadata:
  name: tls-secrets
  namespace: kc-azure-prod
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""
